"""Post-run experience pipeline for the terminal coding agent.

This module provides ``ExperiencePipeline`` — a single coordinator that
orchestrates the full post-run workflow:

    1. Evaluate the completed trajectory deterministically.
    2. Generate a structured LLM reflection.
    3. Persist the trajectory with embedded evaluation and reflection.
    4. Save the experience to long-term memory.

The pipeline is intentionally separate from the agent loop.  It receives a
completed ``AgentResult`` and handles everything that happens *after* execution.
Callers (CLI, test harnesses, scripts) simply pass the result in; the pipeline
decides what to save and where.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Union

from coding_agent.evaluator import EvaluationResult, TrajectoryEvaluator
from coding_agent.memory import Experience, ExperienceMemory
from coding_agent.models import AgentResult
from coding_agent.reflection import ReflectionGenerator, ReflectionResult
from coding_agent.run_record import RunRecord
from coding_agent.trajectory_store import TrajectoryStore


@dataclass
class PipelineResult:
    """Structured output produced by ``ExperiencePipeline.process``.

    Attributes
    ----------
    run_record:
        The ``RunRecord`` trajectory that was processed.
    evaluation:
        Deterministic ``EvaluationResult`` computed for the trajectory.
    reflection:
        Structured ``ReflectionResult`` generated by the LLM.
    experience:
        The ``Experience`` record saved to long-term memory, or ``None`` if
        memory storage was skipped (e.g. when the run was unsuccessful and
        ``only_store_successful`` is ``True``).
    trajectory_path:
        File path where the trajectory JSON was written, or ``None`` if
        trajectory persistence was disabled.
    experience_path:
        File path where the experience JSON was written, or ``None`` if no
        experience was stored.
    errors:
        List of non-fatal error messages encountered during processing.
        The pipeline catches storage and reflection errors so the agent run
        result is always available even when post-processing partially fails.
    """

    run_record: RunRecord
    evaluation: EvaluationResult
    reflection: ReflectionResult
    experience: Optional[Experience] = None
    trajectory_path: Optional[Path] = None
    experience_path: Optional[Path] = None
    errors: list = field(default_factory=list)

    @property
    def success(self) -> bool:
        """``True`` when no non-fatal errors occurred during processing."""
        return len(self.errors) == 0

    @property
    def is_actionable(self) -> bool:
        """Return True when an experience was successfully stored with high confidence."""
        return self.success and self.experience is not None


    def to_dict(self) -> Dict[str, Any]:
        """Return a plain dictionary summary of the pipeline result."""
        return {
            "run_id": self.run_record.run_id,
            "evaluation": self.evaluation.to_dict(),
            "reflection": self.reflection.to_dict(),
            "experience_id": self.experience.experience_id if self.experience else None,
            "trajectory_path": str(self.trajectory_path) if self.trajectory_path else None,
            "experience_path": str(self.experience_path) if self.experience_path else None,
            "errors": list(self.errors),
        }


class ExperiencePipeline:
    """Orchestrates post-run evaluation, reflection, and memory storage.

    This is the central coordinator for the self-improvement feedback loop.
    After each agent run, call :meth:`process` with the ``AgentResult`` and the
    pipeline will:

    - Evaluate the trajectory using deterministic signals.
    - Generate a structured LLM reflection.
    - Persist the trajectory (with evaluation and reflection embedded).
    - Optionally store the experience in long-term memory.

    All steps are wrapped in individual try/except blocks so that a storage
    failure or a reflection API error never prevents the pipeline from
    returning a result with the data it *did* successfully produce.

    Parameters
    ----------
    evaluator:
        ``TrajectoryEvaluator`` instance to use.  A default instance is created
        if not provided.
    reflection_generator:
        ``ReflectionGenerator`` instance.  A default instance is created if not
        provided.
    trajectory_store:
        ``TrajectoryStore`` for persisting run trajectories.  Pass ``None`` to
        disable trajectory persistence.
    memory:
        ``ExperienceMemory`` for long-term storage.  Pass ``None`` to disable
        experience storage.
    only_store_successful:
        When ``True``, only save experiences where ``evaluation.success`` is
        ``True``.  Trajectory persistence is unaffected by this flag.
    enable_reflection:
        When ``False``, skip LLM reflection generation entirely.  A no-op
        placeholder ``ReflectionResult`` is used instead.  Useful in tests or
        when the reflection model is unavailable.
    verbose:
        When ``True``, print brief status messages to stderr during processing.
    """

    def __init__(
        self,
        evaluator: Optional[TrajectoryEvaluator] = None,
        reflection_generator: Optional[ReflectionGenerator] = None,
        trajectory_store: Optional[TrajectoryStore] = None,
        memory: Optional[ExperienceMemory] = None,
        only_store_successful: bool = False,
        enable_reflection: bool = True,
        verbose: bool = False,
    ) -> None:
        self.evaluator = evaluator or TrajectoryEvaluator()
        self.reflection_generator = reflection_generator or ReflectionGenerator()
        self.trajectory_store = trajectory_store
        self.memory = memory
        self.only_store_successful = only_store_successful
        self.enable_reflection = enable_reflection
        self.verbose = verbose

    # ---------------------------------------------------------------------- #
    # Public API                                                               #
    # ---------------------------------------------------------------------- #

    def process(self, result: AgentResult) -> PipelineResult:
        """Run the full post-run pipeline for a completed ``AgentResult``.

        Parameters
        ----------
        result:
            The completed agent result returned by ``Agent.run``.  Must contain
            a populated ``run_record`` attribute.

        Returns
        -------
        PipelineResult
            Structured result with evaluation, reflection, and storage metadata.

        Raises
        ------
        ValueError:
            If ``result.run_record`` is ``None``.
        """
        if result.run_record is None:
            raise ValueError(
                "AgentResult.run_record is None — cannot process a run without a trajectory."
            )

        record: RunRecord = result.run_record
        errors: list = []

        # ------------------------------------------------------------------ #
        # Step 1: Evaluate                                                    #
        # ------------------------------------------------------------------ #
        self._log("Evaluating trajectory …")
        evaluation = self.evaluator.evaluate(record)

        # ------------------------------------------------------------------ #
        # Step 2: Reflect                                                     #
        # ------------------------------------------------------------------ #
        reflection = self._generate_reflection(record, evaluation, errors)

        # ------------------------------------------------------------------ #
        # Step 3: Persist trajectory                                          #
        # ------------------------------------------------------------------ #
        trajectory_path = self._save_trajectory(record, evaluation, reflection, errors)

        # ------------------------------------------------------------------ #
        # Step 4: Store experience                                            #
        # ------------------------------------------------------------------ #
        experience, experience_path = self._store_experience(
            record, evaluation, reflection, errors
        )

        self._log(
            f"Pipeline complete — score={evaluation.score:.2f}, "
            f"success={evaluation.success}, errors={len(errors)}"
        )

        return PipelineResult(
            run_record=record,
            evaluation=evaluation,
            reflection=reflection,
            experience=experience,
            trajectory_path=trajectory_path,
            experience_path=experience_path,
            errors=errors,
        )

    def process_record(
        self,
        record: RunRecord,
        task: Optional[str] = None,
    ) -> PipelineResult:
        """Process a raw ``RunRecord`` directly, without an ``AgentResult`` wrapper.

        Useful for post-hoc reprocessing of stored trajectories.

        Parameters
        ----------
        record:
            A completed ``RunRecord`` to evaluate and reflect on.
        task:
            Override task text.  Falls back to ``record.task`` if not given.
        """
        from coding_agent.models import AgentResult  # local import avoids circularity

        if task:
            record.task = task

        fake_result = AgentResult(
            final_response=record.final_response,
            messages=record.messages or [],
            steps_taken=record.steps_taken,
            completed=True,
            run_record=record,
        )
        return self.process(fake_result)

    def batch_process(self, results: list) -> list:
        """Process a batch of AgentResult instances in sequence.

        Parameters
        ----------
        results:
            List of completed ``AgentResult`` objects.

        Returns
        -------
        list[PipelineResult]
            Parallel list of pipeline outputs.
        """
        return [self.process(res) for res in results]


    # ---------------------------------------------------------------------- #
    # Private helpers                                                          #
    # ---------------------------------------------------------------------- #

    def _generate_reflection(
        self,
        record: RunRecord,
        evaluation: EvaluationResult,
        errors: list,
    ) -> ReflectionResult:
        """Generate reflection, returning a blank placeholder on failure."""
        if not self.enable_reflection:
            return ReflectionResult(
                what_worked="Reflection disabled.",
                what_failed="N/A",
                why_it_failed="N/A",
                what_to_do_differently="N/A",
                summary="Reflection was disabled for this pipeline run.",
            )

        self._log("Generating reflection …")
        try:
            return self.reflection_generator.generate(record, evaluation)
        except Exception as exc:
            err_msg = f"Reflection generation failed: {exc}"
            errors.append(err_msg)
            self._log(err_msg)
            return ReflectionResult(
                what_worked="N/A",
                what_failed=f"Reflection error: {exc}",
                why_it_failed="An exception occurred during reflection generation.",
                what_to_do_differently="N/A",
                summary="Reflection could not be generated due to an error.",
            )

    def _save_trajectory(
        self,
        record: RunRecord,
        evaluation: EvaluationResult,
        reflection: ReflectionResult,
        errors: list,
    ) -> Optional[Path]:
        """Persist trajectory to disk, returning the path or None on failure."""
        if self.trajectory_store is None:
            return None

        self._log("Saving trajectory …")
        try:
            path = self.trajectory_store.save(
                record, evaluation=evaluation, reflection=reflection
            )
            return path
        except Exception as exc:
            err_msg = f"Trajectory persistence failed: {exc}"
            errors.append(err_msg)
            self._log(err_msg)
            return None

    def _store_experience(
        self,
        record: RunRecord,
        evaluation: EvaluationResult,
        reflection: ReflectionResult,
        errors: list,
    ):
        """Store experience in long-term memory, returning (experience, path) or (None, None)."""
        if self.memory is None:
            return None, None

        if self.only_store_successful and not evaluation.success:
            self._log(
                "Skipping experience storage (run not successful and "
                "only_store_successful=True)."
            )
            return None, None

        self._log("Storing experience in memory …")
        try:
            experience = self.memory.add(
                task=record.task or "",
                evaluation=evaluation,
                reflection=reflection,
                trajectory_run_id=record.run_id,
            )
            experience_path = self.memory.get_path(experience.experience_id)
            return experience, experience_path
        except Exception as exc:
            err_msg = f"Experience storage failed: {exc}"
            errors.append(err_msg)
            self._log(err_msg)
            return None, None

    def _log(self, message: str) -> None:
        """Conditionally print a status message to stderr."""
        if self.verbose:
            print(f"[pipeline] {message}", file=sys.stderr)
